### ISSUE TITLE
Does not support JUnit 5's @TestInstance

### ISSUE THREAD

**Issue by chrisr3** [osgi/osgi-test#462] opened 2022-02-20 13:51 UTC
I have recently discovered that JUnit 5 allow you to control whether or not it reuses an instance of a test class for all tests, or creates a new instance for each test. However, the `org.osgi:org.osgi.test.junit5` extension artifact doesn’t appear to support `@TestInstance` :cry:.

This test class works:
```kotlin
package com.example.stuff.testing

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.osgi.framework.Bundle
import org.osgi.framework.BundleContext
import org.osgi.service.component.annotations.RequireServiceComponentRuntime
import org.osgi.test.common.annotation.InjectBundleContext
import org.osgi.test.junit5.context.BundleContextExtension

@ExtendWith(value = [ BundleContextExtension::class ])
@RequireServiceComponentRuntime
class WorkingTest {
    companion object {
        @InjectBundleContext
        lateinit var bundleContext: BundleContext

        private lateinit var testBundle: Bundle

        @Suppress("unused")
        @BeforeAll
        @JvmStatic
        fun setup() {
            testBundle = bundleContext.bundle
        }
    }

    @Test
    fun myTest() {
        assertEquals("testing", testBundle.symbolicName)
    }
}
```
whereas this one does not:
```kotlin
package com.example.stuff.testing

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestInstance
import org.junit.jupiter.api.TestInstance.Lifecycle.PER_CLASS
import org.junit.jupiter.api.extension.ExtendWith
import org.osgi.framework.Bundle
import org.osgi.framework.BundleContext
import org.osgi.service.component.annotations.RequireServiceComponentRuntime
import org.osgi.test.common.annotation.InjectBundleContext
import org.osgi.test.junit5.context.BundleContextExtension

@ExtendWith(value = [ BundleContextExtension::class ])
@RequireServiceComponentRuntime
@TestInstance(PER_CLASS)
class NotWorkingTest {
    @InjectBundleContext
    lateinit var bundleContext: BundleContext

    private lateinit var testBundle: Bundle

    @BeforeAll
    fun setup() {
        testBundle = bundleContext.bundle
    }

    @Test
    fun myTest() {
        assertEquals("testing", testBundle.symbolicName)
    }
}
```
The exception in the error case is:
```java
# Execution Finished: NotWorkingTest - [engine:bnd-bundle-engine]/[bundle:testing;1.0.0.SNAPSHOT]/[sub-engine:junit-jupiter]/[class:com.example.stuff.testing.NotWorkingTest] - TestExecutionResult [status = FAILED, throwable = kotlin.UninitializedPropertyAccessException: lateinit property bundleContext has not been initialized]
kotlin.UninitializedPropertyAccessException: lateinit property bundleContext has not been initialized
        at com.example.stuff.testing.NotWorkingTest.setup(NotWorkingTest.kt:26)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        ...
```
which suggests that the injection would have happened in the `@BeforeEach` phase rather than the `@BeforeAll` phase.

`@InjectService` gives similar results.

The point of `@TestInstance(PER_CLASS)` is that `@BeforeAll`/`@AfterAll`-scoped items no longer need to be `static`, and I suspect `org.osgi.test.junit5` is not handling this case.

Cheers,
Chris

**Comment by kriegfrj** [comment] 2022-02-20 23:45
Hi @chrisr3 , thanks for the issue report! I'm glad this library is seeing some real-world use (and with kotlin too - proof of its versatility)!

#### Executive summary:

osgi-test currently supports this scenario, but you must use parameter injection on `@BeforeAll`.

For field injection support, we'd need to either add a field to the current annotation, or else add an alternative annotation. I'm happy to look at adding the field but I'd like some feedback from yourself (as the groundbreaker on this issue) and other core contributors.

#### Detail: 

The issue here is that the injector code has no way of knowing your intention for your field `bundleContext`whether the field it is initializing is intended to have class scope or method scope, as the same annotation is used for both. The only clue it has is to look at whether the annotated field is static or an instance method - if static, it assumes you want it initialized during `@BeforeAll`; if instance it assumes you want it initialized during `@BeforeEach`.

There are a few ways to achieve what you're after:

##### Solution 1: Use parameter injection on `@BeforeAll`

The first way (which is already supported by osgi-test out-of-the-box) is to use parameter injection on your `@BeforeAll` method instead of field injection. Thus something like:
```java
@ExtendWith(value = [ BundleContextExtension::class ])
@RequireServiceComponentRuntime
@TestInstance(PER_CLASS)
class ShouldWorkTest {
    // Don't annotate this method so that the injector doesn't try to initialize it
    lateinit var bundleContext: BundleContext

    private lateinit var testBundle: Bundle

    @BeforeAll
    fun setup(@InjectBundleContext BundleContext bc) {
        bundleContext = bc // You may not even need the field if you don't need access to it outside of this setup method.
        testBundle = bundleContext.bundle
    }

    @Test
    fun myTest() {
        assertEquals("testing", testBundle.symbolicName)
    }
}
```

(Please forgive me if I've messed up something syntactically as I'm not a kotlin expert by any stretch of the imagination...)

##### Solution 2: Extra field on `@InjectBundleContext`

Another possibility would be extend the syntax of the annotation to give a mechanism to specify the intended lifecycle, eg:

```java
@ExtendWith(value = [ BundleContextExtension::class ])
@RequireServiceComponentRuntime
@TestInstance(PER_CLASS)
class MayWorkInAFutureReleaseTest {
    @InjectBundleContext(lifeCycle = BEFORE_ALL)
    lateinit var bundleContext: BundleContext

    private lateinit var testBundle: Bundle

    @BeforeAll
    fun setup() {
        testBundle = bundleContext.bundle
    }

    @Test
    fun myTest() {
        assertEquals("testing", testBundle.symbolicName)
    }
}
```

The injector code would then be able to use this field to determine which phase to inject, and the default would be to use the field's static/instance attribute as the guide (to maintain backward compatibility and the convenience).

##### Solution 3: Specific annotation `@InjectStaticBundleContext`

Another possibility is to us a different annotation:

```java
@ExtendWith(value = [ BundleContextExtension::class ])
@RequireServiceComponentRuntime
@TestInstance(PER_CLASS)
class MayWorkInAFutureReleaseTest {
    @InjectStaticBundleContext
    lateinit var bundleContext: BundleContext

    private lateinit var testBundle: Bundle

    @BeforeAll
    fun setup() {
        testBundle = bundleContext.bundle
    }

    @Test
    fun myTest() {
        assertEquals("testing", testBundle.symbolicName)
    }
}
```

This is very similar conceptually to the previous, but syntactically a bit neater for your use case.

So if we're going to add a new feature to support your use case, my vote is for the extra field - while the different annotation is slightly neater, I think that it will result in some unnecessary duplication (with all the inherent problems this yields) and extra maintenance burden which outweigh the gains. Interested in your feedback on this + feedback from the rest of the osgi-team.

**Comment by chrisr3** [comment] 2022-02-21 09:19
Well, my view is that having declared the test class to use the `PER_CLASS` lifecycle, I would expect _all_ of its instance fields to be initialized prior to JUnit's `@BeforeAll` stage. Haven't I just instructed JUnit that this single instance of the class will be reused across all of its `@Test` methods?

**Comment by bjhargrave** [comment] 2022-02-21 14:22
@kriegfrj Can you work on this for 1.1?

**Comment by kriegfrj** [comment] 2022-02-22 01:47
(Btw, this is a duplicate of #201.)

> I guess the bottom line is that I view @InjectBundleContext, @InjectService etc on fields as part of "test class construction", which is either PER_METHOD or PER_CLASS, according to how the class has been annotated. So no need for either a new annotation, or a new field on the existing annotation: if the test class has been annotated as @TestInstance(PER_CLASS) then inject its fields during @BeforeAll rather than @BeforeEach.

But this is not how Jupiter defines it. As I understand it, one of the main reasons Jupiter introduced the `PER_CLASS` mode was to support the before/after all lifecycle phase in Kotlin and other JVM languages that don't support static methods or variables. But the concept of test instance lifecycle was supposed to be independent of the BeforeAll/Each phases. So much so that test lifecycle can be a global configuration option, and test classes configured with default test instance lifecycle might conceivably be expected to be able to operate the same in either configuration. Changing the extensions to operate in this way would violate this principle.

> I think the best solution is that when @TestInstance(PER_CLASS) is in effect, we inject non-static fields on BeforeAll rather than BeforeEach. Then the fields have a value at BeforeAll time.

But if you do that and you want a test-method-scoped bundle context (which is common), then you'd need to use parameter injection on every such method. This is more burdensome than using parameter injection on a single `@BeforeAll`.

I think an even better option: "when `@TestInstance(PER_CLASS)` is in effect, we inject non-static fields on BeforeAll ~rather than~and BeforeEach". This gives you the best of both worlds. This is what I did for `SoftAssertionsExtension` in AssertJ.

**Comment by chrisr3** [comment] 2022-02-22 09:59
> As I understand it, one of the main reasons Jupiter introduced the PER_CLASS mode was to support the before/after all lifecycle phase in Kotlin and other JVM languages that don't support static methods or variables.

Kotlin clearly _does_ support static methods and variables though, c.f. my `WorkingTest` class. The [JUnit Javadoc](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/TestInstance.html) does mention that `@TestInstance` allows the Kotlin code to be _simplified_, but I don't see anything there to contradict my point.

But anyway,  my opinion is that if someone _chooses_ to annotate a class with `@TestInstance(PER_CLASS)` then they are declaring that they _want_ to re-use the same class instance to execute all of its `@Test` cases, and hence re-use all of that class's fields too.

> I think an even better option: "when @TestInstance(PER_CLASS) is in effect, we inject non-static fields on BeforeAll and BeforeEach".

I don't think I'd expect the fields to be reset between tests if I'd annotated the class as `@TestInstance(PER_CLASS)`, although I suppose I'd be unlikely to notice unless the service being injected were (say) a `PROTOTYPE`.

**Comment by kriegfrj** [comment] 2022-02-22 13:07
> > As I understand it, one of the main reasons Jupiter introduced the PER_CLASS mode was to support the before/after all lifecycle phase in Kotlin and other JVM languages that don't support static methods or variables.
> 
> Kotlin clearly _does_ support static methods and variables though, c.f. my `WorkingTest` class. The [JUnit Javadoc](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/TestInstance.html) does mention that `@TestInstance` allows the Kotlin code to be _simplified_, but I don't see anything there to contradict my point.
> 

You are right; it was nested classes (ie, non- static inner classes) that I was thinking of. 

> But anyway, my opinion is that if someone _chooses_ to annotate a class with `@TestInstance(PER_CLASS)` then they are declaring that they _want_ to re-use the same class instance to execute all of its `@Test` cases, and hence re-use all of that class's fields too.
> 
> > I think an even better option: "when `@TestInstance(PER_CLASS)` is in effect, we inject non-static fields on BeforeAll and BeforeEach".
> 
> I don't think I'd expect the fields to be reset between tests if I'd annotated the class as `@TestInstance(PER_CLASS)`, although I suppose I'd be unlikely to notice unless the service being injected were (say) a `PROTOTYPE`.

OK, I'll go with this. Should have it done by tomorrow.

**Comment by kriegfrj** [comment] 2022-02-23 00:50
😞 

The easiest solution to this *should* be to move the non-static field initialization from a `BeforeEach` callback to a `TestInstancePostProcessor` callback. Unfortunately when I did this, a number of our tests started mysteriously failing.

When I dug deeper I discovered this statement in the [doc](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/TestInstancePostProcessor.html):

> Extensions that implement TestInstancePostProcessor must be registered at the class level.

Since #403 was merged, our tests rely on the meta-annotation on fields rather than explicitly using (eg) `@ExtendWith(BundleContextExtension)`. But because the `TestInstancePostProcessor` *requires* the annotation to be at the class level, using this meta-annotation feature doesn't work (as our `@InjectBundleContext` annotation is on the fields, not the class).

I'll need to find a way around this... (this was supposed to be a quick fix...)

**Closed** 2022-03-03 18:10 UTC
